package entity;
// Generated Jan 17, 2020 4:32:14 PM by Hibernate Tools 4.3.1



/**
 * AutomobilKupacId generated by hbm2java
 */
public class AutomobilKupacId  implements java.io.Serializable {


     private int automobilId;
     private int kupacId;

    public AutomobilKupacId() {
    }

    public AutomobilKupacId(int automobilId, int kupacId) {
       this.automobilId = automobilId;
       this.kupacId = kupacId;
    }
   
    public int getAutomobilId() {
        return this.automobilId;
    }
    
    public void setAutomobilId(int automobilId) {
        this.automobilId = automobilId;
    }
    public int getKupacId() {
        return this.kupacId;
    }
    
    public void setKupacId(int kupacId) {
        this.kupacId = kupacId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AutomobilKupacId) ) return false;
		 AutomobilKupacId castOther = ( AutomobilKupacId ) other; 
         
		 return (this.getAutomobilId()==castOther.getAutomobilId())
 && (this.getKupacId()==castOther.getKupacId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAutomobilId();
         result = 37 * result + this.getKupacId();
         return result;
   }   


}


