package entity;
// Generated Jan 17, 2020 4:32:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AutomobilKupac generated by hbm2java
 */
public class AutomobilKupac  implements java.io.Serializable {


     private AutomobilKupacId id;
     private Automobil automobil;
     private Kupac kupac;
     private String nacinPlacanja;
     private Date datum;

    public AutomobilKupac() {
    }

	
    public AutomobilKupac(AutomobilKupacId id, Automobil automobil, Kupac kupac) {
        this.id = id;
        this.automobil = automobil;
        this.kupac = kupac;
    }
    public AutomobilKupac(AutomobilKupacId id, Automobil automobil, Kupac kupac, String nacinPlacanja, Date datum) {
       this.id = id;
       this.automobil = automobil;
       this.kupac = kupac;
       this.nacinPlacanja = nacinPlacanja;
       this.datum = datum;
    }
   
    public AutomobilKupacId getId() {
        return this.id;
    }
    
    public void setId(AutomobilKupacId id) {
        this.id = id;
    }
    public Automobil getAutomobil() {
        return this.automobil;
    }
    
    public void setAutomobil(Automobil automobil) {
        this.automobil = automobil;
    }
    public Kupac getKupac() {
        return this.kupac;
    }
    
    public void setKupac(Kupac kupac) {
        this.kupac = kupac;
    }
    public String getNacinPlacanja() {
        return this.nacinPlacanja;
    }
    
    public void setNacinPlacanja(String nacinPlacanja) {
        this.nacinPlacanja = nacinPlacanja;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


