package entity;
// Generated Jan 17, 2020 4:32:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kupac generated by hbm2java
 */
public class Kupac  implements java.io.Serializable {


     private Integer id;
     private String ime;
     private String prezime;
     private String kontakt;
     private Set<AutomobilKupac> automobilKupacs = new HashSet<AutomobilKupac>(0);

    public Kupac() {
    }

    public Kupac(String ime, String prezime, String kontakt, Set<AutomobilKupac> automobilKupacs) {
       this.ime = ime;
       this.prezime = prezime;
       this.kontakt = kontakt;
       this.automobilKupacs = automobilKupacs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getKontakt() {
        return this.kontakt;
    }
    
    public void setKontakt(String kontakt) {
        this.kontakt = kontakt;
    }
    public Set<AutomobilKupac> getAutomobilKupacs() {
        return this.automobilKupacs;
    }
    
    public void setAutomobilKupacs(Set<AutomobilKupac> automobilKupacs) {
        this.automobilKupacs = automobilKupacs;
    }




}


